### ISSUE TITLE
C code generation line break issue

### ISSUE THREAD

**Issue by blumenta** [pydy/pydy-code-gen#27]
Hello, while using CythonMatrixGenerator and CMatrixGenerator I stumbled upon the following issue:
the generated C code appears to have some undesirable line breaks which render the code uncompilable. For example, this generated statement 

double pydy_2382 = (1.0L/4.0L)*pydy_1930*pydy_203*pydy_204*pydy_2339*pydy_2
95*pydy_345*pydy_60;

yields the following gcc error:

error: expected ‘,’ or ‘;’ before numeric constant
     95*pydy_345*pydy_60;

Of course there shouldn't be a line break in the middle of the variable name pydy_295. That happens when attempting to compile the C code on my own. When I try using the CythonMatrixGenerator.compile() method, the Exception('Failed to compile and import Cython module.') is raised. 

Is this the correct channel to report such an issue? And in the meantime how do I compile the cython code directly from the files generated by the .write() method? Since there are only 2 such occurrences of this linebreak error I can easily correct the .c file manually.

Thanks in advance,

Alejandro

**Comment by moorepants** [comment]
Alejandro,

This repository is no longer maintained and is only here for historical reasons. All of the code gen stuff has been merged into the main pydy package: https://github.com/pydy/pydy. Can you report this there if it is valid?

**Comment by blumenta** [comment]
Ok, thanks Jason.
